const STARTING_BUDGET=35000,SAVE_KEY="ashbury-row-complete-v1";
const ROOMS={
 exterior:{name:"Exterior",image:"assets/rooms/exterior.webp",corners:[{name:"Front Approach",target:"entry"},{name:"Garden Beds"},{name:"Window Bay"},{name:"Side Path"}]},
 entry:{name:"Entryway",image:"assets/rooms/entry.webp",corners:[{name:"Front Door",target:"exterior"},{name:"Living Arch",target:"living"},{name:"Kitchen Passage",target:"kitchen"},{name:"Bedroom Hall",target:"bedroom"}]},
 living:{name:"Living Room",image:"assets/rooms/living.webp",corners:[{name:"Window Wall"},{name:"Dining Doorway",target:"dining"},{name:"Patio Door",target:"patio"},{name:"Entry Arch",target:"entry"}]},
 kitchen:{name:"Kitchen",image:"assets/rooms/kitchen.webp",corners:[{name:"Island View"},{name:"Dining Doorway",target:"dining"},{name:"Patio Door",target:"patio"},{name:"Entry Passage",target:"entry"}]},
 dining:{name:"Dining Room",image:"assets/rooms/dining.webp",corners:[{name:"Gallery Wall"},{name:"Living Arch",target:"living"},{name:"Kitchen Doorway",target:"kitchen"},{name:"Entry Passage",target:"entry"}]},
 bedroom:{name:"Bedroom",image:"assets/rooms/bedroom.webp",corners:[{name:"Window Wall"},{name:"Bed Wall"},{name:"Dressing Wall"},{name:"Hall Door",target:"entry"}]},
 bathroom:{name:"Bathroom",image:"assets/rooms/bathroom.webp",corners:[{name:"Vanity Wall"},{name:"Shower Wall"},{name:"Linen Wall"},{name:"Hall Door",target:"entry"}]},
 office:{name:"Office",image:"assets/rooms/office.webp",corners:[{name:"Window Wall"},{name:"Desk Wall"},{name:"Library Wall"},{name:"Hall Door",target:"entry"}]},
 patio:{name:"Patio",image:"assets/rooms/patio.webp",corners:[{name:"Garden Wall"},{name:"Lounge Wall"},{name:"Kitchen Door",target:"kitchen"},{name:"Living Door",target:"living"}]}
};
const ALL_ROOMS=Object.keys(ROOMS),INTERIORS=["entry","living","kitchen","dining","bedroom","bathroom","office"],ANY=[...ALL_ROOMS];
const raw=[
 ["club-chair","Cognac Club Chair",1299,"Seating",["living","bedroom","office"],"floor",230,"warm"],["tailored-sofa","Charcoal Tailored Sofa",2399,"Seating",["living"],"floor",290,"modern"],["coffee-table","Walnut Coffee Table",849,"Tables",["living"],"floor",250,"warm",1],["side-table","Round Side Table",399,"Tables",["living","bedroom","office"],"floor",170,"warm",1],["media-console","Walnut Media Console",1199,"Storage",["living"],"floor",270,"modern",1],["bookcase-tall","Tall Walnut Bookcase",999,"Storage",["living","office","bedroom"],"floor",205,"warm",1],
 ["queen-bed","Charcoal Queen Bed",2499,"Bedroom",["bedroom"],"floor",310,"modern"],["nightstand","Walnut Nightstand",449,"Bedroom",["bedroom"],"floor",170,"warm",1],["dresser","Six-Drawer Dresser",1399,"Bedroom",["bedroom"],"floor",260,"warm",1],["wardrobe","Walnut Wardrobe",1899,"Bedroom",["bedroom"],"floor",240,"luxury",1],["bed-bench","Upholstered Bed Bench",749,"Bedroom",["bedroom"],"floor",225,"luxury",1],["floor-mirror","Brass Floor Mirror",599,"Decor",["bedroom","entry"],"floor",205,"luxury"],
 ["dining-table","Six-Seat Dining Table",1899,"Tables",["dining"],"floor",300,"warm",1],["dining-chair","Cognac Dining Chair",349,"Seating",["dining","entry"],"floor",190,"warm"],["bar-stool","Charcoal Bar Stool",249,"Seating",["kitchen"],"floor",175,"modern"],["serving-console","Walnut Serving Console",899,"Storage",["dining"],"floor",255,"warm",1],["pendant-light","Sculptural Pendant",579,"Lighting",["dining","kitchen"],"ceiling",210,"luxury"],["drinks-trolley","Walnut Drinks Trolley",649,"Tables",["dining","living"],"floor",190,"luxury",1],
 ["writing-desk","Walnut Writing Desk",1099,"Office",["office"],"floor",265,"warm",1],["office-chair","Ergonomic Office Chair",699,"Office",["office"],"floor",200,"modern"],["bookcase-wide","Wide Low Bookcase",899,"Storage",["office","living"],"floor",270,"modern",1],["filing-cabinet","Walnut Filing Cabinet",379,"Office",["office"],"floor",170,"modern",1],["reading-chair","Charcoal Reading Chair",899,"Seating",["office","living","bedroom"],"floor",215,"modern"],["task-floor-lamp","Brass Task Lamp",329,"Lighting",["office","living","bedroom"],"floor",190,"luxury"],
 ["cream-rug","Handwoven Cream Rug",699,"Decor",INTERIORS,"floor",285,"organic"],["fiddle-fig","Fiddle-Leaf Fig",189,"Plants",ANY,"floor",205,"organic"],["abstract-art","Earthform No. 4",375,"Wall",INTERIORS,"wall",180,"modern"],["ceramic-vase","Sculptural Ceramic Vase",145,"Decor",INTERIORS,"surface",120,"organic"],["table-lamp","Obsidian Table Lamp",279,"Lighting",INTERIORS,"surface",135,"luxury"],["woven-basket","Woven Floor Basket",119,"Storage",INTERIORS,"floor",150,"organic"],
 ["refrigerator","French-Door Refrigerator",2299,"Appliances",["kitchen"],"floor",245,"modern"],["range","Gas Convection Range",1599,"Appliances",["kitchen"],"floor",225,"modern"],["dishwasher","Quiet Dishwasher",899,"Appliances",["kitchen"],"floor",205,"modern"],["microwave","Countertop Microwave",249,"Appliances",["kitchen"],"surface",150,"modern"],["bath-cabinet-white","Stone Bath Cabinet",599,"Bathroom",["bathroom"],"floor",185,"modern",1],["laundry-hamper","Lidded Laundry Hamper",139,"Bathroom",["bathroom","bedroom"],"floor",150,"organic"],
 ["olive-planter","Olive Tree Planter",289,"Exterior",["exterior","patio"],"floor",220,"organic"],["garden-gnome","Bronze Garden Gnome",89,"Exterior",["exterior","patio"],"floor",120,"playful"],["parcel-mailbox","Parcel Mailbox",329,"Exterior",["exterior"],"floor",180,"modern"],["porch-bench","Walnut Porch Bench",749,"Exterior",["exterior","patio"],"floor",250,"warm",1],["patio-chair","Woven Patio Chair",549,"Exterior",["patio"],"floor",215,"modern"],["patio-table","Stone Patio Table",399,"Exterior",["patio"],"floor",175,"organic",1],
 ["espresso-machine","Matte Espresso Machine",699,"Countertop",["kitchen"],"surface",145,"modern"],["toaster","Cream Two-Slot Toaster",129,"Countertop",["kitchen"],"surface",125,"warm"],["stand-mixer","Stainless Stand Mixer",449,"Countertop",["kitchen"],"surface",155,"modern"],["air-fryer","Compact Air Fryer",179,"Countertop",["kitchen"],"surface",140,"modern"],["knife-block","Walnut Knife Block",199,"Countertop",["kitchen"],"surface",125,"warm"],["electric-kettle","Cream Electric Kettle",99,"Countertop",["kitchen"],"surface",125,"warm"],
 ["bath-stool","Walnut Bath Stool",219,"Bathroom",["bathroom"],"floor",150,"warm",1],["towel-ladder","Walnut Towel Ladder",289,"Bathroom",["bathroom"],"floor",190,"warm"],["bath-cabinet-walnut","Walnut Linen Cabinet",799,"Bathroom",["bathroom"],"floor",195,"warm",1],["bath-hamper-charcoal","Charcoal Bath Hamper",169,"Bathroom",["bathroom"],"floor",150,"modern"],["potted-fern","Potted Boston Fern",119,"Plants",["bathroom","patio","entry"],"floor",175,"organic"],["round-mirror","Round Brass Mirror",399,"Wall",["bathroom","entry","bedroom"],"wall",180,"luxury"],
 ["television","65-inch Gallery Television",1099,"Media",["living","bedroom"],"floor",245,"modern"],
 ["record-console","Walnut Record Console",899,"Media",["living","office"],"floor",235,"warm",1],
 ["soundbar","Slim Charcoal Soundbar",349,"Media",["living","bedroom"],"surface",155,"modern"],
 ["wall-clock","Walnut Wall Clock",189,"Wall",INTERIORS,"wall",155,"warm"],
 ["brass-sculpture","Brass Loop Sculpture",229,"Decor",INTERIORS,"surface",125,"luxury"],
 ["landscape-art","Misty Valley Landscape",449,"Wall",INTERIORS,"wall",190,"warm"],
 ["storage-tote","Lidded Storage Tote",79,"Storage",INTERIORS,"floor",175,"modern"],
 ["coat-rack","Walnut Coat Rack",249,"Entry",["entry","bedroom"],"floor",185,"warm"],
 ["shoe-bench","Upholstered Shoe Bench",499,"Entry",["entry","bedroom"],"floor",220,"warm",1],
 ["floating-shelf","Floating Walnut Shelf",169,"Wall",INTERIORS,"wall",205,"warm",1],
 ["umbrella-stand","Black Umbrella Stand",129,"Entry",["entry"],"floor",135,"modern"],
 ["storage-ottoman","Round Storage Ottoman",329,"Storage",["living","bedroom","office"],"floor",175,"modern",1],
 ["ceiling-fan","Walnut Ceiling Fan",399,"Lighting",INTERIORS,"ceiling",245,"modern"],
 ["ceiling-light","Low-profile Brass Light",249,"Lighting",INTERIORS,"ceiling",185,"luxury"],
 ["wall-sconce","Architectural Wall Sconce",179,"Lighting",ANY,"wall",145,"modern"],
 ["wall-mailbox","Wall-mounted Mailbox",159,"Exterior",["exterior"],"wall",165,"modern"],
 ["hose-reel","Garden Hose Reel",189,"Exterior",["exterior","patio"],"wall",175,"modern"],
 ["gas-grill","Premium Gas Grill",799,"Exterior",["patio"],"floor",240,"modern"]
];
const PRODUCTS=raw.map(([id,name,price,category,rooms,placement,size,style,support=0])=>({id,name,price,category,rooms,placement,size,style,support:!!support,image:`assets/items/${id}.webp`}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={welcome:$("#welcome"),scene:$("#scene"),bg:$("#scene-bg"),layer:$("#object-layer"),door:$("#door-hotspot"),doorLabel:$("#door-label"),doorAction:$("#door-action"),hint:$("#scene-hint"),room:$("#room-label"),corner:$("#corner-label"),dots:$("#corner-dots"),budget:$("#budget"),roomScore:$("#room-score"),catalog:$("#catalog"),grid:$("#product-grid"),cats:$("#categories"),owned:$("#owned-count"),roomsCount:$("#rooms-count"),inspector:$("#inspector"),selectedName:$("#selected-name"),selectedPrice:$("#selected-price"),scale:$("#scale-control"),tilt:$("#tilt-control"),rotate:$("#rotate-control"),map:$("#map-dialog"),roomGrid:$("#room-grid"),offers:$("#offers-dialog"),offersGrid:$("#offers"),sale:$("#sale-dialog"),toast:$("#toast")};
let state={budget:STARTING_BUDGET,room:"exterior",corner:0,objects:[],selected:null,mode:"shop",category:"All",sold:false},db,drag,doorTap=0,swipeStart;
const money=n=>`₢${Math.round(n).toLocaleString("en-US")}`,product=id=>PRODUCTS.find(p=>p.id===id),currentCorner=()=>ROOMS[state.room].corners[state.corner];
function toast(msg){el.toast.textContent=msg;el.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("show"),1900)}
function tone(freq){try{tone.ctx??=new AudioContext();const o=tone.ctx.createOscillator(),g=tone.ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.022,tone.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,tone.ctx.currentTime+.11);o.connect(g).connect(tone.ctx.destination);o.start();o.stop(tone.ctx.currentTime+.12)}catch{}}
function openDB(){return new Promise(ok=>{const q=indexedDB.open("nth-house",2);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains("save"))q.result.createObjectStore("save")};q.onsuccess=()=>{db=q.result;ok()};q.onerror=()=>ok()})}
function load(){return new Promise(ok=>{if(!db)return ok();const q=db.transaction("save").objectStore("save").get(SAVE_KEY);q.onsuccess=()=>{if(q.result)state={...state,...q.result,selected:null};ok()};q.onerror=()=>ok()})}
function save(){if(db)db.transaction("save","readwrite").objectStore("save").put({...state,selected:null},SAVE_KEY)}
async function enterGame(){try{await document.documentElement.requestFullscreen?.();await screen.orientation?.lock?.("landscape")}catch{}if(matchMedia("(orientation:landscape)").matches)el.welcome.classList.add("hidden");setTimeout(()=>el.hint.classList.add("fade"),3200)}
function roomObjects(room=state.room){return state.objects.filter(o=>!o.stored&&o.room===room)}
function roomScore(room){const os=roomObjects(room),cats=new Set(os.map(o=>product(o.productId)?.category)),spent=os.reduce((n,o)=>n+(product(o.productId)?.price||0),0);return Math.min(100,Math.round(os.length*16+cats.size*8+Math.min(18,spent/500)))}
function readyRooms(){return ALL_ROOMS.filter(r=>roomScore(r)>=50).length}
function imageStyle(p){return `background-image:url('${p.image}')`}
function render(){
 const room=ROOMS[state.room],corner=currentCorner();el.scene.style.setProperty("--scene-image",`url('${room.image}')`);el.scene.className=`scene corner-${state.corner}`;
 el.room.textContent=`ASHBURY ROW · ${room.name.toUpperCase()}`;el.corner.textContent=corner.name.toUpperCase();el.budget.textContent=money(state.budget);el.roomScore.textContent=`${roomScore(state.room)}%`;
 el.dots.innerHTML=room.corners.map((_,i)=>`<i class="${i===state.corner?"active":""}"></i>`).join("");
 const target=corner.target;el.door.hidden=!target;el.doorAction.hidden=!target;if(target){const targetName=ROOMS[target].name.toUpperCase();el.doorLabel.textContent=`DOUBLE TAP · ${targetName}`;el.doorAction.textContent=`ENTER ${targetName}`;el.door.style.setProperty("--door-x",state.corner%2?"69%":"70%");el.door.style.setProperty("--door-y","18%");el.door.style.setProperty("--door-w","18%");el.door.style.setProperty("--door-h","64%");}
 el.hint.textContent=target?`Double tap the doorway to enter ${ROOMS[target].name}`:"Swipe to see the next corner";
 renderObjects();renderCatalog();renderMap();save();
}
function renderObjects(){
 el.layer.innerHTML="";state.objects.filter(o=>!o.stored&&o.room===state.room&&o.corner===state.corner).sort((a,b)=>a.z-b.z).forEach(o=>{const p=product(o.productId);if(!p)return;const node=document.createElement("div");node.className=`placed-object${o.uid===state.selected?" selected":""}`;node.dataset.uid=o.uid;node.dataset.placement=p.placement;node.style.cssText=`${imageStyle(p)};--object-size:${p.size}px;left:${o.x}%;top:${o.y}%;z-index:${o.z};transform:translate(-50%,-50%) perspective(760px) rotateY(${o.facing}deg) rotateZ(${o.tilt}deg) scaleX(${o.flip}) scale(${o.scale})`;node.setAttribute("role","button");node.setAttribute("aria-label",p.name);node.addEventListener("pointerdown",startDrag);el.layer.append(node)});renderInspector();
}
function renderInspector(){const o=selected(),p=o&&product(o.productId);el.inspector.classList.toggle("visible",!!o);el.inspector.setAttribute("aria-hidden",String(!o));if(!o)return;el.selectedName.textContent=p.name;el.selectedPrice.textContent=money(p.price);el.scale.value=Math.round(o.scale*100);el.tilt.value=o.tilt;el.rotate.value=o.facing}
function categories(){return ["All",...new Set(PRODUCTS.map(p=>p.category))]}
function renderCatalog(){
 el.owned.textContent=state.objects.length;el.roomsCount.textContent=`${readyRooms()}/9`;
 if(state.mode==="rooms"){el.cats.innerHTML="";el.grid.innerHTML=ALL_ROOMS.map(r=>`<button class="room-card" data-room="${r}"><span class="room-thumb" style="background-image:url('${ROOMS[r].image}')"></span><span><strong>${ROOMS[r].name}</strong><small>${roomObjects(r).length} pieces placed</small></span><span>${roomScore(r)}%</span></button>`).join("");el.grid.querySelectorAll(".room-card").forEach(b=>b.onclick=()=>goRoom(b.dataset.room));return}
 el.cats.innerHTML=categories().map(c=>`<button class="${state.category===c?"active":""}" data-category="${c}">${c}</button>`).join("");el.cats.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCatalog()});
 let pool=state.mode==="shop"?PRODUCTS:state.objects.filter(o=>o.stored).map(o=>({...product(o.productId),uid:o.uid}));pool=pool.filter(p=>state.category==="All"||p.category===state.category);
 el.grid.innerHTML=pool.length?pool.map(p=>`<button class="product-card" data-id="${p.id}" ${p.uid?`data-uid="${p.uid}"`:""}><div class="product-visual" style="${imageStyle(p)}"></div><small>${p.category.toUpperCase()}</small><div class="product-meta"><strong>${p.name}</strong><span>${p.uid?"PLACE":money(p.price)}</span></div></button>`).join(""):`<div class="empty-state">No stored pieces in this category.</div>`;
 el.grid.querySelectorAll(".product-card").forEach(b=>b.onclick=()=>b.dataset.uid?placeOwned(b.dataset.uid):buy(b.dataset.id));
}
function renderMap(){el.roomGrid.innerHTML=ALL_ROOMS.map(r=>`<button class="map-room ${r===state.room?"current":""}" data-room="${r}"><div class="map-room-img" style="background-image:url('${ROOMS[r].image}')"></div><div class="map-room-meta"><strong>${ROOMS[r].name}</strong><span>${roomScore(r)}%</span></div></button>`).join("");el.roomGrid.querySelectorAll(".map-room").forEach(b=>b.onclick=()=>{el.map.close();goRoom(b.dataset.room)})}
function buy(id){const p=product(id);if(!p||state.budget<p.price)return toast("Not enough Cruzeiros for this piece");state.budget-=p.price;const allowed=p.rooms.includes(state.room),room=allowed?state.room:p.rooms[0],stored=!allowed;const o={uid:crypto.randomUUID(),productId:id,room,corner:allowed?state.corner:0,x:50,y:p.placement==="wall"?40:p.placement==="ceiling"?27:p.placement==="surface"?58:73,scale:1,tilt:0,facing:0,flip:1,z:state.objects.length+1,stored,parentUid:null};state.objects.push(o);state.selected=stored?null:o.uid;render();toast(stored?`${p.name} saved to Owned · suited for ${ROOMS[room].name}`:`${p.name} placed · ${money(state.budget)} left`);tone(330)}
function placeOwned(uid){const o=state.objects.find(x=>x.uid===uid),p=o&&product(o.productId);if(!o)return;if(!p.rooms.includes(state.room)){toast(`${p.name} is suited for ${p.rooms.map(r=>ROOMS[r].name).join(", ")}`);return}o.stored=false;o.room=state.room;o.corner=state.corner;o.x=50;o.y=p.placement==="wall"?40:p.placement==="ceiling"?27:p.placement==="surface"?58:73;o.parentUid=null;state.selected=uid;closeCatalog();render();toast("Piece ready to position")}
function selected(){return state.objects.find(o=>o.uid===state.selected)}
function startDrag(e){e.stopPropagation();const o=state.objects.find(x=>x.uid===e.currentTarget.dataset.uid);state.selected=o.uid;drag={o,node:e.currentTarget,id:e.pointerId,lastX:o.x,lastY:o.y};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add("dragging","selected");renderInspector()}
el.layer.addEventListener("pointermove",e=>{if(!drag||drag.id!==e.pointerId)return;const r=el.scene.getBoundingClientRect(),p=product(drag.o.productId),oldX=drag.o.x,oldY=drag.o.y;drag.o.x=Math.max(3,Math.min(97,(e.clientX-r.left)/r.width*100));let y=(e.clientY-r.top)/r.height*100;if(p.placement==="wall")y=Math.max(19,Math.min(61,y));else if(p.placement==="ceiling")y=Math.max(12,Math.min(42,y));else if(p.placement==="surface")y=Math.max(37,Math.min(73,y));else y=Math.max(46,Math.min(88,y));drag.o.y=y;if(p.support){const dx=drag.o.x-oldX,dy=drag.o.y-oldY;state.objects.filter(c=>c.parentUid===drag.o.uid).forEach(c=>{c.x+=dx;c.y+=dy})}drag.node.style.left=`${drag.o.x}%`;drag.node.style.top=`${drag.o.y}%`});
el.layer.addEventListener("pointerup",()=>{if(!drag)return;snapToSurface(drag.o);drag.node.classList.remove("dragging");drag=null;renderObjects();save()});
function snapToSurface(o){const p=product(o.productId);if(p.placement!=="surface")return;const supports=state.objects.filter(x=>!x.stored&&x.room===o.room&&x.corner===o.corner&&x.uid!==o.uid&&product(x.productId)?.support);let best=null,dist=99;for(const s of supports){const d=Math.hypot(o.x-s.x,(o.y-s.y)*.7);if(d<dist){dist=d;best=s}}if(best&&dist<16){o.parentUid=best.uid;o.x=best.x;o.y=Math.max(26,best.y-11*best.scale);o.z=best.z+1;toast(`Placed on ${product(best.productId).name}`)}else o.parentUid=null}
function mutate(fn){const o=selected();if(!o)return;fn(o);renderObjects();save()}
el.scale.oninput=e=>mutate(o=>o.scale=Number(e.target.value)/100);el.tilt.oninput=e=>mutate(o=>o.tilt=Number(e.target.value));el.rotate.oninput=e=>mutate(o=>o.facing=Number(e.target.value));
$("#flip-object").onclick=()=>mutate(o=>o.flip*=-1);$("#layer-down").onclick=()=>mutate(o=>o.z=Math.max(1,o.z-1));$("#layer-up").onclick=()=>mutate(o=>o.z+=1);
$("#store-object").onclick=()=>{const o=selected();if(!o)return;o.stored=true;state.objects.filter(c=>c.parentUid===o.uid).forEach(c=>{c.stored=true;c.parentUid=null});state.selected=null;render();toast("Moved to Owned")};
$("#sell-object").onclick=()=>{const o=selected();if(!o)return;const p=product(o.productId),refund=Math.round(p.price*.65);state.objects.filter(c=>c.parentUid===o.uid).forEach(c=>{c.stored=true;c.parentUid=null});state.objects=state.objects.filter(x=>x.uid!==o.uid);state.budget+=refund;state.selected=null;render();toast(`${p.name} sold for ${money(refund)}`)};
function changeView(d){state.corner=(state.corner+d+4)%4;state.selected=null;el.hint.classList.remove("fade");render();tone(180)}
function goRoom(room){if(!ROOMS[room])return;state.room=room;state.corner=0;state.selected=null;closeCatalog();render();toast(ROOMS[room].name);tone(240)}
function enterDoor(){const target=currentCorner().target;if(target)goRoom(target)}
function openCatalog(){el.catalog.classList.add("open");el.catalog.setAttribute("aria-hidden","false");$("#shop-toggle").setAttribute("aria-expanded","true")}
function closeCatalog(){el.catalog.classList.remove("open");el.catalog.setAttribute("aria-hidden","true");$("#shop-toggle").setAttribute("aria-expanded","false")}
const BUYERS=[{name:"Mara & Ellis",taste:"Warm materials · layered comfort",style:"warm",mult:1.015},{name:"Devon Price",taste:"Modern restraint · useful storage",style:"modern",mult:1.04},{name:"The Bennett Group",taste:"Luxury finishes · statement lighting",style:"luxury",mult:1.07}];
function appraisal(){const placed=state.objects.filter(o=>!o.stored),spent=STARTING_BUDGET-state.budget,ready=readyRooms(),styles=new Set(placed.map(o=>product(o.productId)?.style));const score=Math.min(100,Math.round(ready*7+placed.length*.65+styles.size*3+Math.min(15,spent/1900)));$("#design-score").textContent=`${score}/100`;$("#spent-total").textContent=money(spent);$("#ready-total").textContent=`${ready}/9`;const qualified=ready===9&&state.budget<=2500;el.offersGrid.innerHTML=BUYERS.map((b,i)=>{const matches=placed.filter(o=>product(o.productId)?.style===b.style).length,offer=Math.round((284000+spent*.78+score*480+matches*575)*b.mult/100)*100;return `<article class="offer ${i===2?"best":""}"><h3>${b.name}</h3><p>${b.taste}</p><strong>${money(offer)}</strong><button data-buyer="${b.name}" data-offer="${offer}" ${qualified?"":"disabled"}>ACCEPT OFFER</button></article>`}).join("");$("#offer-note").textContent=qualified?"The property is showing-ready. Choose the buyer who best rewards your design.":`Finish all nine spaces and reduce the remaining budget to ₢2,500 or less. ${ready}/9 rooms are ready.`;el.offersGrid.querySelectorAll("button").forEach(b=>b.onclick=()=>completeSale(b.dataset.buyer,Number(b.dataset.offer)));el.offers.showModal()}
function completeSale(buyer,offer){state.sold=true;save();el.offers.close();$("#sale-title").textContent=`${buyer} chose your home.`;$("#sale-price").textContent=money(offer);$("#sale-copy").textContent=`Your furnishing investment transformed Ashbury Row into a ${roomObjects().length?"distinctive":"refined"} fully furnished property.`;el.sale.showModal();tone(540)}
function registerAgentTools(){const c=document.modelContext;if(!c?.registerTool)return;const empty={type:"object",additionalProperties:false};c.registerTool({name:"get_house_status",title:"Get house status",description:"Read the Nth House budget, current room, room readiness, and furnishing counts.",inputSchema:empty,annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({budget:state.budget,currentRoom:state.room,roomsReady:readyRooms(),owned:state.objects.length,placed:state.objects.filter(o=>!o.stored).length})});c.registerTool({name:"navigate_to_room",title:"Navigate to room",description:"Move to one room in Ashbury Row.",inputSchema:{type:"object",properties:{room:{type:"string",enum:ALL_ROOMS}},required:["room"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({room})=>{goRoom(room);return{room}}});c.registerTool({name:"purchase_furnishing",title:"Purchase furnishing",description:"Purchase a catalog furnishing by product id.",inputSchema:{type:"object",properties:{productId:{type:"string"}},required:["productId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({productId})=>{const p=product(productId);if(!p)throw Error("Unknown product");if(state.budget<p.price)throw Error("Insufficient budget");buy(productId);return{purchased:p.name,budget:state.budget}}})}
$("#enter-game").onclick=enterGame;$("#shop-toggle").onclick=openCatalog;$("#shop-close").onclick=closeCatalog;$("#prev-view").onclick=()=>changeView(-1);$("#next-view").onclick=()=>changeView(1);$("#room-map-button").onclick=$("#map-toggle").onclick=()=>el.map.showModal();$("#map-close").onclick=()=>el.map.close();el.doorAction.onclick=enterDoor;
el.door.addEventListener("pointerup",()=>{const now=Date.now();if(now-doorTap<430)enterDoor();else toast("Tap once more to enter");doorTap=now});el.door.addEventListener("dblclick",enterDoor);
$("#open-house").onclick=appraisal;$("#offers-close").onclick=()=>el.offers.close();$("#continue-designing").onclick=()=>el.sale.close();
$$('.catalog-tabs button').forEach(b=>b.onclick=()=>{$$('.catalog-tabs button').forEach(x=>x.classList.toggle("active",x===b));state.mode=b.dataset.mode;state.category="All";renderCatalog()});
el.scene.addEventListener("pointerdown",e=>{if(e.target.closest(".placed-object,.door-hotspot,.view-controls"))return;swipeStart={x:e.clientX,y:e.clientY};state.selected=null;renderObjects()});el.scene.addEventListener("pointerup",e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy))changeView(dx<0?1:-1)});
window.addEventListener("keydown",e=>{if(e.key==="Escape"){closeCatalog();state.selected=null;renderObjects()}if(e.key==="ArrowLeft")changeView(-1);if(e.key==="ArrowRight")changeView(1)});window.addEventListener("orientationchange",()=>{if(matchMedia("(orientation:landscape)").matches)el.welcome.classList.add("hidden")});
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
(async()=>{await openDB();await load();render();registerAgentTools()})();
