const STARTING_BUDGET=35000,SAVE_KEY="ashbury-row-complete-v1";
const ROOMS={
 exterior:{name:"Exterior",image:"assets/rooms/exterior.webp",corners:[{name:"Front Approach",target:"entry"}]},
 entry:{name:"Entryway",corners:[{name:"Front Door",target:"exterior"},{name:"Open Living Room",target:"living"},{name:"Kitchen Archway",target:"kitchen"},{name:"Bedroom Hall",target:"bedroom",returnFrom:["bedroom","bathroom","office"]}]},
 living:{name:"Living Room",corners:[{name:"Entry Opening",target:"entry"},{name:"Feature Wall"},{name:"Dining Alcove",target:"dining"},{name:"Window Wall"}]},
 kitchen:{name:"Kitchen",corners:[{name:"Entry Archway",target:"entry"},{name:"Island View"},{name:"Dining Archway",target:"dining"},{name:"Patio Door",target:"patio"}]},
 dining:{name:"Dining Room",corners:[{name:"Living Room Door",target:"living"},{name:"Window Gallery"},{name:"Kitchen Archway",target:"kitchen"},{name:"Feature Wall"}]},
 bedroom:{name:"Bedroom",corners:[{name:"Hall Door",target:"entry"},{name:"Window Wall"},{name:"Bed Wall"},{name:"Dressing Alcove"}]},
 bathroom:{name:"Bathroom",corners:[{name:"Hall Door",target:"entry"},{name:"Vanity Wall"},{name:"Shower Wall"},{name:"Linen Alcove"}]},
 office:{name:"Office",corners:[{name:"Hall Door",target:"entry"},{name:"Window Wall"},{name:"Desk Wall"},{name:"Library Alcove"}]},
 patio:{name:"Patio",corners:[{name:"Kitchen Door",target:"kitchen"},{name:"Garden Wall"},{name:"Lounge Wall"},{name:"Living Room Door",target:"living"}]}
};
Object.entries(ROOMS).forEach(([id,room])=>room.corners.forEach((corner,index)=>corner.image=room.image||`assets/rooms/views/${id}-${index}.webp`));
const ALL_ROOMS=Object.keys(ROOMS),INTERIORS=["entry","living","kitchen","dining","bedroom","bathroom","office"],ANY=[...ALL_ROOMS];
const raw=[
 ["club-chair","Cognac Club Chair",1299,"Seating",["living","bedroom","office"],"floor",230,"warm"],["tailored-sofa","Charcoal Tailored Sofa",2399,"Seating",["living"],"floor",290,"modern"],["coffee-table","Walnut Coffee Table",849,"Tables",["living"],"floor",250,"warm",1],["side-table","Round Side Table",399,"Tables",["living","bedroom","office"],"floor",170,"warm",1],["media-console","Walnut Media Console",1199,"Storage",["living"],"floor",270,"modern",1],["bookcase-tall","Tall Walnut Bookcase",999,"Storage",["living","office","bedroom"],"floor",205,"warm",1],
 ["queen-bed","Charcoal Queen Bed",2499,"Bedroom",["bedroom"],"floor",310,"modern"],["nightstand","Walnut Nightstand",449,"Bedroom",["bedroom"],"floor",170,"warm",1],["dresser","Six-Drawer Dresser",1399,"Bedroom",["bedroom"],"floor",260,"warm",1],["wardrobe","Walnut Wardrobe",1899,"Bedroom",["bedroom"],"floor",240,"luxury",1],["bed-bench","Upholstered Bed Bench",749,"Bedroom",["bedroom"],"floor",225,"luxury",1],["floor-mirror","Brass Floor Mirror",599,"Decor",["bedroom","entry"],"floor",205,"luxury"],
 ["dining-table","Six-Seat Dining Table",1899,"Tables",["dining"],"floor",300,"warm",1],["dining-chair","Cognac Dining Chair",349,"Seating",["dining","entry"],"floor",190,"warm"],["bar-stool","Charcoal Bar Stool",249,"Seating",["kitchen"],"floor",175,"modern"],["serving-console","Walnut Serving Console",899,"Storage",["dining"],"floor",255,"warm",1],["pendant-light","Sculptural Pendant",579,"Lighting",["dining","kitchen"],"ceiling",210,"luxury"],["drinks-trolley","Walnut Drinks Trolley",649,"Tables",["dining","living"],"floor",190,"luxury",1],
 ["writing-desk","Walnut Writing Desk",1099,"Office",["office"],"floor",265,"warm",1],["office-chair","Ergonomic Office Chair",699,"Office",["office"],"floor",200,"modern"],["bookcase-wide","Wide Low Bookcase",899,"Storage",["office","living"],"floor",270,"modern",1],["filing-cabinet","Walnut Filing Cabinet",379,"Office",["office"],"floor",170,"modern",1],["reading-chair","Charcoal Reading Chair",899,"Seating",["office","living","bedroom"],"floor",215,"modern"],["task-floor-lamp","Brass Task Lamp",329,"Lighting",["office","living","bedroom"],"floor",190,"luxury"],
 ["cream-rug","Handwoven Cream Rug",699,"Decor",INTERIORS,"floor",285,"organic"],["fiddle-fig","Fiddle-Leaf Fig",189,"Plants",ANY,"floor",205,"organic"],["abstract-art","Earthform No. 4",375,"Wall",INTERIORS,"wall",180,"modern"],["ceramic-vase","Sculptural Ceramic Vase",145,"Decor",INTERIORS,"surface",120,"organic"],["table-lamp","Obsidian Table Lamp",279,"Lighting",INTERIORS,"surface",135,"luxury"],["woven-basket","Woven Floor Basket",119,"Storage",INTERIORS,"floor",150,"organic"],
 ["refrigerator","French-Door Refrigerator",2299,"Appliances",["kitchen"],"floor",245,"modern"],["range","Gas Convection Range",1599,"Appliances",["kitchen"],"floor",225,"modern"],["dishwasher","Quiet Dishwasher",899,"Appliances",["kitchen"],"floor",205,"modern"],["microwave","Countertop Microwave",249,"Appliances",["kitchen"],"surface",150,"modern"],["bath-cabinet-white","Stone Bath Cabinet",599,"Bathroom",["bathroom"],"floor",185,"modern",1],["laundry-hamper","Lidded Laundry Hamper",139,"Bathroom",["bathroom","bedroom"],"floor",150,"organic"],
 ["olive-planter","Olive Tree Planter",289,"Exterior",["exterior","patio"],"floor",220,"organic"],["garden-gnome","Bronze Garden Gnome",89,"Exterior",["exterior","patio"],"floor",120,"playful"],["parcel-mailbox","Parcel Mailbox",329,"Exterior",["exterior"],"floor",180,"modern"],["porch-bench","Walnut Porch Bench",749,"Exterior",["exterior","patio"],"floor",250,"warm",1],["patio-chair","Woven Patio Chair",549,"Exterior",["patio"],"floor",215,"modern"],["patio-table","Stone Patio Table",399,"Exterior",["patio"],"floor",175,"organic",1],
 ["espresso-machine","Matte Espresso Machine",699,"Countertop",["kitchen"],"surface",145,"modern"],["toaster","Cream Two-Slot Toaster",129,"Countertop",["kitchen"],"surface",125,"warm"],["stand-mixer","Stainless Stand Mixer",449,"Countertop",["kitchen"],"surface",155,"modern"],["air-fryer","Compact Air Fryer",179,"Countertop",["kitchen"],"surface",140,"modern"],["knife-block","Walnut Knife Block",199,"Countertop",["kitchen"],"surface",125,"warm"],["electric-kettle","Cream Electric Kettle",99,"Countertop",["kitchen"],"surface",125,"warm"],
 ["bath-stool","Walnut Bath Stool",219,"Bathroom",["bathroom"],"floor",150,"warm",1],["towel-ladder","Walnut Towel Ladder",289,"Bathroom",["bathroom"],"floor",190,"warm"],["bath-cabinet-walnut","Walnut Linen Cabinet",799,"Bathroom",["bathroom"],"floor",195,"warm",1],["bath-hamper-charcoal","Charcoal Bath Hamper",169,"Bathroom",["bathroom"],"floor",150,"modern"],["potted-fern","Potted Boston Fern",119,"Plants",["bathroom","patio","entry"],"floor",175,"organic"],["round-mirror","Round Brass Mirror",399,"Wall",["bathroom","entry","bedroom"],"wall",180,"luxury"],
 ["television","65-inch Gallery Television",1099,"Media",["living","bedroom"],"floor",245,"modern"],
 ["record-console","Walnut Record Console",899,"Media",["living","office"],"floor",235,"warm",1],
 ["soundbar","Slim Charcoal Soundbar",349,"Media",["living","bedroom"],"surface",155,"modern"],
 ["wall-clock","Walnut Wall Clock",189,"Wall",INTERIORS,"wall",155,"warm"],
 ["brass-sculpture","Brass Loop Sculpture",229,"Decor",INTERIORS,"surface",125,"luxury"],
 ["landscape-art","Misty Valley Landscape",449,"Wall",INTERIORS,"wall",190,"warm"],
 ["storage-tote","Lidded Storage Tote",79,"Storage",INTERIORS,"floor",175,"modern"],
 ["coat-rack","Walnut Coat Rack",249,"Entry",["entry","bedroom"],"floor",185,"warm"],
 ["shoe-bench","Upholstered Shoe Bench",499,"Entry",["entry","bedroom"],"floor",220,"warm",1],
 ["floating-shelf","Floating Walnut Shelf",169,"Wall",INTERIORS,"wall",205,"warm",1],
 ["umbrella-stand","Black Umbrella Stand",129,"Entry",["entry"],"floor",135,"modern"],
 ["storage-ottoman","Round Storage Ottoman",329,"Storage",["living","bedroom","office"],"floor",175,"modern",1],
 ["ceiling-fan","Walnut Ceiling Fan",399,"Lighting",INTERIORS,"ceiling",245,"modern"],
 ["ceiling-light","Low-profile Brass Light",249,"Lighting",INTERIORS,"ceiling",185,"luxury"],
 ["wall-sconce","Architectural Wall Sconce",179,"Lighting",ANY,"wall",145,"modern"],
 ["wall-mailbox","Wall-mounted Mailbox",159,"Exterior",["exterior"],"wall",165,"modern"],
 ["hose-reel","Garden Hose Reel",189,"Exterior",["exterior","patio"],"wall",175,"modern"],
 ["gas-grill","Premium Gas Grill",799,"Exterior",["patio"],"floor",240,"modern"],
 ["copper-gutters","Aged Copper Gutter Kit",1850,"Exterior",["exterior"],"wall",250,"luxury"],
 ["brass-address-plaque","Cast Brass Address Plaque",145,"Exterior",["exterior"],"wall",125,"luxury"],
 ["entry-runner","Charcoal Woven Runner",329,"Decor",["entry"],"floor",265,"warm"],
 ["entry-hook-rail","Walnut Entry Hook Rail",169,"Entry",["entry"],"wall",180,"warm"],
 ["modular-sectional","Warm Gray Modular Sectional",3199,"Seating",["living"],"floor",320,"modern"],
 ["brass-arc-lamp","Arched Brass Floor Lamp",429,"Lighting",["living"],"floor",225,"luxury"],
 ["hanging-pot-rack","Walnut Hanging Pot Rack",699,"Countertop",["kitchen"],"ceiling",220,"warm"],
 ["travertine-fruit-bowl","Travertine Pear Bowl",189,"Decor",["kitchen","dining"],"surface",125,"organic"],
 ["oval-dining-table","Oval Stone Dining Table",2299,"Tables",["dining"],"floor",305,"luxury",1],
 ["smoked-glass-chandelier","Smoked Glass Chandelier",1299,"Lighting",["dining"],"ceiling",220,"luxury"],
 ["canopy-bed","Walnut Canopy Bed",2899,"Bedroom",["bedroom"],"floor",315,"warm"],
 ["bedroom-vanity","Walnut Dressing Vanity",1099,"Bedroom",["bedroom"],"floor",235,"warm",1],
 ["soaking-tub","Sculptural Soaking Tub",2199,"Bathroom",["bathroom"],"floor",260,"luxury"],
 ["heated-towel-rail","Brass Heated Towel Rail",549,"Bathroom",["bathroom"],"wall",175,"luxury"],
 ["executive-desk","Fluted Walnut Executive Desk",1799,"Office",["office"],"floor",285,"luxury",1],
 ["articulated-desk-lamp","Articulated Brass Desk Lamp",249,"Lighting",["office"],"surface",135,"warm"],
 ["outdoor-sectional","Woven Outdoor Sectional",2699,"Exterior",["patio"],"floor",310,"modern"],
 ["stone-fire-pit","Cast Stone Fire Pit",899,"Exterior",["patio"],"floor",210,"organic"]
];
const FLAT_IDS=new Set(["cream-rug","entry-runner"]);
const PRODUCTS=raw.map(([id,name,price,category,rooms,placement,size,style,support=0])=>({id,name,price,category,rooms,placement,size,style,support:!!support,flat:FLAT_IDS.has(id),image:`assets/items/${id}.webp`}));
const INSTALLATION_SLOTS={
 kitchen:[{
  id:"refrigerator-bay",label:"INSTALL IN REFRIGERATOR BAY",accepts:["refrigerator"],installView:1,
  projections:{
   1:{x:76.8,y:53,scale:.92,tilt:0,facing:0,flip:1,z:2,image:"assets/items/refrigerator-installed-front.webp"}
  },
  hotspots:{
   1:{x:76.8,y:50,w:16,h:54}
  }
 }]
};
const FIXED_PRODUCT_IDS=new Set(Object.values(INSTALLATION_SLOTS).flat().flatMap(slot=>slot.accepts));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const el={welcome:$("#welcome"),scene:$("#scene"),bg:$("#scene-bg"),slots:$("#slot-layer"),fixedLayer:$("#fixed-object-layer"),layer:$("#object-layer"),door:$("#door-hotspot"),doorLabel:$("#door-label"),doorAction:$("#door-action"),room:$("#room-label"),corner:$("#corner-label"),dots:$("#corner-dots"),budget:$("#budget"),roomScore:$("#room-score"),catalog:$("#catalog"),grid:$("#product-grid"),cats:$("#categories"),owned:$("#owned-count"),roomsCount:$("#rooms-count"),inspector:$("#inspector"),placementNote:$("#placement-note"),selectedName:$("#selected-name"),selectedPrice:$("#selected-price"),scale:$("#scale-control"),tilt:$("#tilt-control"),rotate:$("#rotate-control"),rotateLabel:$("#rotate-label"),map:$("#map-dialog"),roomGrid:$("#room-grid"),offers:$("#offers-dialog"),offersGrid:$("#offers"),sale:$("#sale-dialog"),toast:$("#toast"),openHouse:$("#open-house"),shopToggle:$("#shop-toggle"),prevView:$("#prev-view"),nextView:$("#next-view")};
let state={budget:STARTING_BUDGET,room:"exterior",corner:0,objects:[],selected:null,pendingUid:null,mode:"shop",category:"All",sold:false,scoreCaps:{}},db,drag,doorTap=0,swipeStart;
const money=n=>`₢${Math.round(n).toLocaleString("en-US")}`,product=id=>PRODUCTS.find(p=>p.id===id),currentCorner=()=>ROOMS[state.room].corners[state.corner];
const slotsForRoom=room=>INSTALLATION_SLOTS[room]||[];
const slotById=(room,id)=>slotsForRoom(room).find(slot=>slot.id===id);
const openSlotFor=(room,productId)=>slotsForRoom(room).find(slot=>slot.accepts.includes(productId)&&!state.objects.some(o=>!o.stored&&o.room===room&&o.slotId===slot.id));
const fixedProduct=p=>!!p&&FIXED_PRODUCT_IDS.has(p.id);
function migrateKitchenInstallations(){
 const slot=slotById("kitchen","refrigerator-bay");if(!slot)return;
 const installed=state.objects.find(o=>!o.stored&&o.room==="kitchen"&&o.slotId===slot.id);
 if(installed)return;
 const legacy=state.objects.find(o=>!o.stored&&o.room==="kitchen"&&o.productId==="refrigerator");
 if(legacy){legacy.slotId=slot.id;legacy.corner=null;legacy.x=50;legacy.y=50;legacy.scale=1;legacy.tilt=0;legacy.facing=0;legacy.flip=1;legacy.parentUid=null}
}
function toast(msg){el.toast.textContent=msg;el.toast.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove("show"),1900)}
function tone(freq){try{tone.ctx??=new AudioContext();const o=tone.ctx.createOscillator(),g=tone.ctx.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.022,tone.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,tone.ctx.currentTime+.11);o.connect(g).connect(tone.ctx.destination);o.start();o.stop(tone.ctx.currentTime+.12)}catch{}}
function openDB(){return new Promise(ok=>{const q=indexedDB.open("nth-house",2);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains("save"))q.result.createObjectStore("save")};q.onsuccess=()=>{db=q.result;ok()};q.onerror=()=>ok()})}
function load(){return new Promise(ok=>{if(!db)return ok();const q=db.transaction("save").objectStore("save").get(SAVE_KEY);q.onsuccess=()=>{if(q.result)state={...state,...q.result,selected:null,pendingUid:null};migrateKitchenInstallations();ok()};q.onerror=()=>ok()})}
function save(){if(db)db.transaction("save","readwrite").objectStore("save").put({...state,selected:null},SAVE_KEY)}
async function enterGame(){try{await document.documentElement.requestFullscreen?.();await screen.orientation?.lock?.("landscape")}catch{}if(matchMedia("(orientation:landscape)").matches)el.welcome.classList.add("hidden")}
function roomObjects(room=state.room){return state.objects.filter(o=>!o.stored&&o.room===room)}
function roomScore(room){const os=roomObjects(room),cats=new Set(os.map(o=>product(o.productId)?.category)),spent=os.reduce((n,o)=>n+(product(o.productId)?.price||0),0),base=Math.min(100,Math.round(os.length*16+cats.size*8+Math.min(18,spent/500)));return Math.min(base,state.scoreCaps?.[room]??100)}
function debitRoomScore(room,count=1){state.scoreCaps??={};state.scoreCaps[room]=Math.max(0,roomScore(room)-16*count)}
function creditRoomScore(room,count=1){state.scoreCaps??={};state.scoreCaps[room]=Math.min(100,(state.scoreCaps[room]??100)+16*count)}
function readyRooms(){return ALL_ROOMS.filter(r=>roomScore(r)===100).length}
function houseCompletion(){return Math.round(ALL_ROOMS.reduce((sum,r)=>sum+roomScore(r),0)/ALL_ROOMS.length)}
function imageStyle(p){return `background-image:url('${p.image}')`}
function render(){
 const room=ROOMS[state.room];state.corner=Math.min(state.corner,room.corners.length-1);const corner=currentCorner();el.scene.style.setProperty("--scene-image",`url('${corner.image}')`);el.scene.className=`scene room-${state.room} corner-${state.corner}${room.corners.length===1?" single-view":""}`;
 el.room.textContent=`ASHBURY ROW · ${room.name.toUpperCase()}`;el.corner.textContent=corner.name.toUpperCase();el.budget.textContent=money(state.budget);el.roomScore.textContent=`${roomScore(state.room)}%`;
 el.dots.innerHTML=room.corners.length>1?room.corners.map((_,i)=>`<i class="${i===state.corner?"active":""}"></i>`).join(""):"";el.prevView.hidden=room.corners.length===1;el.nextView.hidden=room.corners.length===1;
 const target=corner.target;el.door.hidden=!target;el.doorAction.hidden=!target;if(target){const targetName=ROOMS[target].name.toUpperCase();el.doorLabel.textContent=`DOUBLE TAP · ${targetName}`;el.doorAction.textContent=`ENTER ${targetName}`;el.door.style.setProperty("--door-x",state.corner%2?"69%":"70%");el.door.style.setProperty("--door-y","18%");el.door.style.setProperty("--door-w","18%");el.door.style.setProperty("--door-h","64%");}
 const complete=houseCompletion();el.openHouse.disabled=complete<100;el.openHouse.title=complete<100?`House is ${complete}% complete`:"Begin the open house";
 renderSlots();renderObjects();renderCatalog();renderMap();save();
}
function renderSlots(){
 el.slots.innerHTML="";const o=state.objects.find(x=>x.uid===state.pendingUid),p=o&&product(o.productId);if(!o||!p||state.room!=="kitchen")return;
 const candidates=slotsForRoom(state.room).filter(slot=>slot.accepts.includes(p.id)&&!state.objects.some(x=>x.uid!==o.uid&&!x.stored&&x.room===state.room&&x.slotId===slot.id));
 candidates.forEach(slot=>{const hit=slot.hotspots?.[state.corner];if(!hit)return;const button=document.createElement("button");button.className="placement-slot";button.style.cssText=`left:${hit.x}%;top:${hit.y}%;width:${hit.w}%;height:${hit.h}%`;button.innerHTML=`<span>${slot.label}</span>`;button.setAttribute("aria-label",slot.label);button.addEventListener("pointerdown",e=>e.stopPropagation());button.addEventListener("pointerup",e=>e.stopPropagation());button.onclick=e=>{e.stopPropagation();installInSlot(o,slot)};el.slots.append(button)});
}
function beginInstallation(o){const p=product(o.productId),slot=openSlotFor("kitchen",p.id);if(!slot)return toast("That architectural slot is already occupied");if(state.room!=="kitchen")return toast(`${p.name} added to Owned · install it from the kitchen`);state.corner=slot.installView;state.pendingUid=o.uid;state.selected=null;closeCatalog();render();toast(`Tap the highlighted ${slot.label.toLowerCase().replace("install in ","")}`);tone(300)}
function installInSlot(o,slot){creditRoomScore("kitchen");o.stored=false;o.room="kitchen";o.corner=null;o.slotId=slot.id;o.parentUid=null;o.x=50;o.y=50;o.scale=1;o.tilt=0;o.facing=0;o.flip=1;o.z=2;state.pendingUid=null;state.selected=o.uid;render();toast(`${product(o.productId).name} installed · visible from matching viewpoints`);tone(420)}
function renderObjects(){
 el.layer.innerHTML="";el.fixedLayer.innerHTML="";state.objects.filter(o=>{if(o.stored||o.room!==state.room)return false;if(!o.slotId)return o.corner===state.corner;return !!slotById(o.room,o.slotId)?.projections?.[state.corner]}).map(o=>{const projection=o.slotId?slotById(o.room,o.slotId).projections[state.corner]:o;return{o,projection}}).sort((a,b)=>a.projection.z-b.projection.z).forEach(({o,projection:q})=>{const p=product(o.productId);if(!p)return;const node=document.createElement("div");node.className=`placed-object${o.uid===state.selected?" selected":""}${p.flat?" flat":""}${o.slotId?" installed":""}`;node.dataset.uid=o.uid;node.dataset.placement=p.placement;node.dataset.fixed=o.slotId?"true":"false";const rotation=p.flat?`rotateX(${q.tilt}deg) rotateZ(${q.facing}deg)`:`rotateY(${q.facing}deg) rotateZ(${q.tilt}deg)`;const image=q.image?`background-image:url('${q.image}')`:imageStyle(p);node.style.cssText=`${image};--object-size:${p.size}px;left:${q.x}%;top:${q.y}%;z-index:${q.z};transform:translate(-50%,-50%) perspective(760px) ${rotation} scaleX(${q.flip}) scale(${q.scale})`;node.setAttribute("role","button");node.setAttribute("aria-label",o.slotId?`${p.name}, fixed installation`:p.name);node.addEventListener("pointerdown",startDrag);(o.slotId?el.fixedLayer:el.layer).append(node)});renderInspector();
}
function renderInspector(){const o=selected(),p=o&&product(o.productId),fixed=!!o?.slotId;el.inspector.classList.toggle("visible",!!o);el.inspector.classList.toggle("fixed-installation",fixed);el.inspector.setAttribute("aria-hidden",String(!o));if(!o)return;el.placementNote.hidden=!fixed;el.selectedName.textContent=p.name;el.selectedPrice.textContent=money(p.price);el.scale.value=Math.round(o.scale*100);el.tilt.value=o.tilt;el.rotate.min=p.flat?-180:-65;el.rotate.max=p.flat?180:65;el.rotateLabel.textContent=p.flat?"ROTATE · 2D":"ROTATE · 2.5D";el.rotate.value=o.facing}
function categories(){return ["All",...new Set(PRODUCTS.map(p=>p.category))]}
function renderCatalog(){
 el.owned.textContent=state.objects.length;el.roomsCount.textContent=`${readyRooms()}/9`;
 if(state.mode==="rooms"){el.cats.innerHTML="";el.grid.innerHTML=ALL_ROOMS.map(r=>`<button class="room-card" data-room="${r}"><span class="room-thumb" style="background-image:url('${ROOMS[r].corners[0].image}')"></span><span><strong>${ROOMS[r].name}</strong><small>${roomObjects(r).length} pieces placed</small></span><span>${roomScore(r)}%</span></button>`).join("");el.grid.querySelectorAll(".room-card").forEach(b=>b.onclick=()=>goRoom(b.dataset.room));return}
 el.cats.innerHTML=categories().map(c=>`<button class="${state.category===c?"active":""}" data-category="${c}">${c}</button>`).join("");el.cats.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCatalog()});
 let pool=state.mode==="shop"?PRODUCTS:state.objects.filter(o=>o.stored).map(o=>({...product(o.productId),uid:o.uid}));pool=pool.filter(p=>state.category==="All"||p.category===state.category);
 el.grid.innerHTML=pool.length?pool.map(p=>`<button class="product-card" data-id="${p.id}" ${p.uid?`data-uid="${p.uid}"`:""}><div class="product-visual" style="${imageStyle(p)}"></div><small>${p.category.toUpperCase()}</small><div class="product-meta"><strong>${p.name}</strong><span>${p.uid?"PLACE":money(p.price)}</span></div></button>`).join(""):`<div class="empty-state">No stored pieces in this category.</div>`;
 el.grid.querySelectorAll(".product-card").forEach(b=>b.onclick=()=>b.dataset.uid?placeOwned(b.dataset.uid):buy(b.dataset.id));
}
function renderMap(){el.roomGrid.innerHTML=ALL_ROOMS.map(r=>`<button class="map-room ${r===state.room?"current":""}" data-room="${r}"><div class="map-room-img" style="background-image:url('${ROOMS[r].corners[0].image}')"></div><div class="map-room-meta"><strong>${ROOMS[r].name}</strong><span>${roomScore(r)}%</span></div></button>`).join("");el.roomGrid.querySelectorAll(".map-room").forEach(b=>b.onclick=()=>{el.map.close();goRoom(b.dataset.room)})}
function buy(id){const p=product(id);if(!p||state.budget<p.price)return toast("Not enough Cruzeiros for this piece");if(fixedProduct(p)&&!openSlotFor("kitchen",p.id))return toast("The refrigerator bay is already occupied");state.budget-=p.price;const fixed=fixedProduct(p),o={uid:crypto.randomUUID(),productId:id,room:fixed?"kitchen":state.room,corner:fixed?null:state.corner,x:50,y:p.placement==="wall"?40:p.placement==="ceiling"?27:p.placement==="surface"?58:73,scale:1,tilt:0,facing:0,flip:1,z:state.objects.length+1,stored:fixed,parentUid:null,slotId:null};state.objects.push(o);if(fixed){render();beginInstallation(o);return}creditRoomScore(state.room);state.selected=o.uid;render();toast(`${p.name} placed · ${money(state.budget)} left`);tone(330)}
function placeOwned(uid){const o=state.objects.find(x=>x.uid===uid),p=o&&product(o.productId);if(!o)return;if(fixedProduct(p)){beginInstallation(o);return}creditRoomScore(state.room);o.stored=false;o.room=state.room;o.corner=state.corner;o.slotId=null;o.x=50;o.y=p.placement==="wall"?40:p.placement==="ceiling"?27:p.placement==="surface"?58:73;o.parentUid=null;state.selected=uid;closeCatalog();render();toast("Piece ready to position")}
function selected(){return state.objects.find(o=>o.uid===state.selected)}
function startDrag(e){e.stopPropagation();const o=state.objects.find(x=>x.uid===e.currentTarget.dataset.uid);state.selected=o.uid;if(o.slotId){renderObjects();return}drag={o,node:e.currentTarget,id:e.pointerId,lastX:o.x,lastY:o.y};e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add("dragging","selected");renderInspector()}
el.layer.addEventListener("pointermove",e=>{if(!drag||drag.id!==e.pointerId)return;const r=el.scene.getBoundingClientRect(),p=product(drag.o.productId),oldX=drag.o.x,oldY=drag.o.y;drag.o.x=Math.max(3,Math.min(97,(e.clientX-r.left)/r.width*100));let y=(e.clientY-r.top)/r.height*100;if(p.placement==="wall")y=Math.max(19,Math.min(61,y));else if(p.placement==="ceiling")y=Math.max(12,Math.min(42,y));else if(p.placement==="surface")y=Math.max(37,Math.min(73,y));else y=Math.max(46,Math.min(88,y));drag.o.y=y;if(p.support){const dx=drag.o.x-oldX,dy=drag.o.y-oldY;state.objects.filter(c=>c.parentUid===drag.o.uid).forEach(c=>{c.x+=dx;c.y+=dy})}drag.node.style.left=`${drag.o.x}%`;drag.node.style.top=`${drag.o.y}%`});
el.layer.addEventListener("pointerup",()=>{if(!drag)return;snapToSurface(drag.o);drag.node.classList.remove("dragging");drag=null;renderObjects();save()});
function snapToSurface(o){const p=product(o.productId);if(p.placement!=="surface")return;const supports=state.objects.filter(x=>!x.stored&&x.room===o.room&&x.corner===o.corner&&x.uid!==o.uid&&product(x.productId)?.support);let best=null,dist=99;for(const s of supports){const d=Math.hypot(o.x-s.x,(o.y-s.y)*.7);if(d<dist){dist=d;best=s}}if(best&&dist<16){o.parentUid=best.uid;o.x=best.x;o.y=Math.max(26,best.y-11*best.scale);o.z=best.z+1;toast(`Placed on ${product(best.productId).name}`)}else o.parentUid=null}
function mutate(fn){const o=selected();if(!o)return;fn(o);renderObjects();save()}
el.scale.oninput=e=>mutate(o=>o.scale=Number(e.target.value)/100);el.tilt.oninput=e=>mutate(o=>o.tilt=Number(e.target.value));el.rotate.oninput=e=>mutate(o=>o.facing=Number(e.target.value));
$("#flip-object").onclick=()=>mutate(o=>o.flip*=-1);$("#layer-down").onclick=()=>mutate(o=>o.z=Math.max(1,o.z-1));$("#layer-up").onclick=()=>mutate(o=>o.z+=1);
$("#store-object").onclick=()=>{const o=selected();if(!o)return;const children=state.objects.filter(c=>c.parentUid===o.uid&&!c.stored);debitRoomScore(o.room,1+children.length);o.stored=true;o.slotId=null;o.corner=null;children.forEach(c=>{c.stored=true;c.parentUid=null});state.selected=null;render();toast("Moved to Owned · room score updated")};
$("#sell-object").onclick=()=>{const o=selected();if(!o)return;const p=product(o.productId),refund=Math.round(p.price*.65),children=state.objects.filter(c=>c.parentUid===o.uid&&!c.stored);debitRoomScore(o.room,1+children.length);children.forEach(c=>{c.stored=true;c.parentUid=null});state.objects=state.objects.filter(x=>x.uid!==o.uid);state.budget+=refund;state.selected=null;render();toast(`${p.name} sold for ${money(refund)} · room score updated`)};
function changeView(d){const count=ROOMS[state.room].corners.length;if(count<2)return;state.corner=(state.corner+d+count)%count;state.selected=null;render();tone(180)}
function goRoom(room,from=state.room){if(!ROOMS[room])return;if(room!=="kitchen")state.pendingUid=null;state.room=room;const returnView=ROOMS[room].corners.findIndex(c=>c.target===from||c.returnFrom?.includes(from));state.corner=returnView>=0?returnView:0;state.selected=null;closeCatalog();render();toast(ROOMS[room].name);tone(240)}
function enterDoor(){const target=currentCorner().target;if(target)goRoom(target,state.room)}
function openCatalog(){el.catalog.classList.add("open");el.catalog.setAttribute("aria-hidden","false");el.shopToggle.setAttribute("aria-expanded","true");el.shopToggle.hidden=true}
function closeCatalog(){el.catalog.classList.remove("open");el.catalog.setAttribute("aria-hidden","true");el.shopToggle.setAttribute("aria-expanded","false");el.shopToggle.hidden=false}
const BUYERS=[{name:"Mara & Ellis",taste:"Warm materials · layered comfort",style:"warm",mult:1.015},{name:"Devon Price",taste:"Modern restraint · useful storage",style:"modern",mult:1.04},{name:"The Bennett Group",taste:"Luxury finishes · statement lighting",style:"luxury",mult:1.07}];
function appraisal(){if(houseCompletion()<100)return toast(`Finish the house before opening it · ${houseCompletion()}% complete`);const placed=state.objects.filter(o=>!o.stored),spent=STARTING_BUDGET-state.budget,ready=readyRooms(),styles=new Set(placed.map(o=>product(o.productId)?.style));const score=Math.min(100,Math.round(ready*7+placed.length*.65+styles.size*3+Math.min(15,spent/1900)));$("#design-score").textContent=`${score}/100`;$("#spent-total").textContent=money(spent);$("#ready-total").textContent=`${ready}/9`;el.offersGrid.innerHTML=BUYERS.map((b,i)=>{const matches=placed.filter(o=>product(o.productId)?.style===b.style).length,offer=Math.round((284000+spent*.78+score*480+matches*575)*b.mult/100)*100;return `<article class="offer ${i===2?"best":""}"><h3>${b.name}</h3><p>${b.taste}</p><strong>${money(offer)}</strong><button data-buyer="${b.name}" data-offer="${offer}">ACCEPT OFFER</button></article>`}).join("");$("#offer-note").textContent="The property is 100% showing-ready. Choose the buyer who best rewards your design.";el.offersGrid.querySelectorAll("button").forEach(b=>b.onclick=()=>completeSale(b.dataset.buyer,Number(b.dataset.offer)));el.offers.showModal()}
function completeSale(buyer,offer){state.sold=true;save();el.offers.close();$("#sale-title").textContent=`${buyer} chose your home.`;$("#sale-price").textContent=money(offer);$("#sale-copy").textContent=`Your furnishing investment transformed Ashbury Row into a ${roomObjects().length?"distinctive":"refined"} fully furnished property.`;el.sale.showModal();tone(540)}
function registerAgentTools(){const c=document.modelContext;if(!c?.registerTool)return;const empty={type:"object",additionalProperties:false};c.registerTool({name:"get_house_status",title:"Get house status",description:"Read the Nth House budget, current room, room readiness, and furnishing counts.",inputSchema:empty,annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({budget:state.budget,currentRoom:state.room,roomsReady:readyRooms(),owned:state.objects.length,placed:state.objects.filter(o=>!o.stored).length})});c.registerTool({name:"navigate_to_room",title:"Navigate to room",description:"Move to one room in Ashbury Row.",inputSchema:{type:"object",properties:{room:{type:"string",enum:ALL_ROOMS}},required:["room"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({room})=>{goRoom(room);return{room}}});c.registerTool({name:"purchase_furnishing",title:"Purchase furnishing",description:"Purchase a catalog furnishing by product id.",inputSchema:{type:"object",properties:{productId:{type:"string"}},required:["productId"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:({productId})=>{const p=product(productId);if(!p)throw Error("Unknown product");if(state.budget<p.price)throw Error("Insufficient budget");buy(productId);return{purchased:p.name,budget:state.budget}}})}
$("#enter-game").onclick=enterGame;$("#shop-toggle").onclick=openCatalog;$("#shop-close").onclick=closeCatalog;$("#prev-view").onclick=()=>changeView(-1);$("#next-view").onclick=()=>changeView(1);$("#room-map-button").onclick=$("#map-toggle").onclick=()=>el.map.showModal();$("#map-close").onclick=()=>el.map.close();el.doorAction.onclick=enterDoor;
$("#open-house").onclick=appraisal;$("#offers-close").onclick=()=>el.offers.close();$("#continue-designing").onclick=()=>el.sale.close();
$$('.catalog-tabs button').forEach(b=>b.onclick=()=>{$$('.catalog-tabs button').forEach(x=>x.classList.toggle("active",x===b));state.mode=b.dataset.mode;state.category="All";renderCatalog()});
el.scene.addEventListener("pointerdown",e=>{if(e.target.closest(".placed-object,.placement-slot,.view-controls"))return;swipeStart={x:e.clientX,y:e.clientY};state.selected=null;renderObjects()});el.scene.addEventListener("pointerup",e=>{if(!swipeStart)return;const dx=e.clientX-swipeStart.x,dy=e.clientY-swipeStart.y;swipeStart=null;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)){changeView(dx<0?1:-1);return}if(Math.hypot(dx,dy)<20&&currentCorner().target){const now=Date.now();if(now-doorTap<520)enterDoor();else toast("Double tap to enter");doorTap=now}});
window.addEventListener("keydown",e=>{if(e.key==="Escape"){closeCatalog();state.selected=null;renderObjects()}if(e.key==="ArrowLeft")changeView(-1);if(e.key==="ArrowRight")changeView(1)});window.addEventListener("orientationchange",()=>{if(matchMedia("(orientation:landscape)").matches)el.welcome.classList.add("hidden")});
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
(async()=>{await openDB();await load();render();registerAgentTools()})();
